# setup git-achievements
export PATH=~/code/git-achievements:$PATH
alias git=git-achievements

# Paydici db population
alias minpop='rake db:populate RESET=1 MINIMAL=1'
alias maxpop='rake db:populate RESET=1'

# for rspec XHTML validation
export NET=true

# quick login to slicehost screen session
alias kaylee-screen='ssh -t kaylee screen -r'
alias ifs-ssh='ssh ftpifsaccess@ifs'

export PATH="/Library/Frameworks/Python.framework/Versions/Current/bin:${PATH}"

export PYTHONPATH=/Users/reidab/Web/Django/src/trunk:/Users/reidab/Web/Django/projects
export PATH=/www/jruby/bin:/opt/local/bin:/opt/local/lib/postgresql84/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH

export PATH=/usr/local/git/bin:$PATH
export MANPATH=/usr/local/git/man:$MANPATH

# -- start rip config -- #
RIPDIR=/Users/reidab/.rip
RUBYLIB="$RUBYLIB:$RIPDIR/active/lib"
PATH="$PATH:$RIPDIR/active/bin"
export RIPDIR RUBYLIB PATH
# -- end rip config -- #

# MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

if [[ -s /Users/reidab/.rvm/scripts/rvm ]] ; then source /Users/reidab/.rvm/scripts/rvm ; fi

#autojump
#This shell snippet sets the prompt command and the necessary aliases

_autojump() 
{
        local cur
        COMPREPLY=()
        unset COMP_WORDS[0] #remove "j" from the array
        cur=${COMP_WORDS[*]}
        IFS=$'\n' read -d '' -a COMPREPLY < <(autojump --bash --completion "$cur")
        return 0
}
complete -F _autojump j
AUTOJUMP='(autojump -a "$(pwd -P)"&)>/dev/null'
if [[ ! $PROMPT_COMMAND =~ autojump ]]; then
  export PROMPT_COMMAND="${PROMPT_COMMAND:-:} && $AUTOJUMP"
fi 
alias jumpstat="autojump --stat"
function j { new_path="$(autojump $@)";if [ -n "$new_path" ]; then echo -e "\\033[31m${new_path}\\033[0m"; cd "$new_path";fi }